### ISSUE TITLE
Add fusion of Conv2D+Batchnorm+ReLU

### ISSUE THREAD

**Issue by jmduarte** [hls4ml-finn-mlperftiny/CIFAR10#1]
- Add fusion of Conv2D+Batchnorm+ReLU

**Comment by oliviaweng** [comment]
Here's the fused Conv2D+BN+ReLU we applied on top of the FIFO optimized model, which we synthesized in Vivado HLS 2020.1: available [here](https://drive.google.com/file/d/1M1V4pBlebij7PGXLdm_ZqEiIbu3XRRvH/view?usp=sharing) 

Files changed:
* `firmware/parameters.h`: We modified certain the structs of type `nnet::dense_config` to include a flag `merged_relu` for merging the relu layer or not and the right typedef for the output of that layer.
* `firmware/myproject.cpp`: We remove the extraneous ReLU layers.
* `firmware/nnet_utils/nnet_dense_resource.h`: The code below comment `// Dense (without ReLU)` is the default for dense layers. The code below comment `// Dense (with ReLU)` has our fused Dense+ReLU implementation. `dense_resource()` checks the `merged_relu` flag in the `dense_config` and calls the appropriate dense function (either with ReLU or without ReLU).

We manually made these changes to the Vivado 2020.1 project linked in this PR [here](https://github.com/hls4ml-finn-mlperftiny/CIFAR10/pull/4).

The code for automatically applying this optimization during HLS generation is forthcoming. That will be created as a PR for hls4ml itself, so for this repo, we'll probably only add the updated `convert.py` script that works with our fork of hls4ml. 
Let me know if that works for you, or if you'd prefer something else, since I see the current `environment.yml` uses Nicolo's hls4ml fork, so we might need to consolidate our changes. To do this all automatically, we'd have to apply the relu fusion optimization first since that occurs during HLS code generation, whereas the fifo optimization occurs after during cosim.

**Comment by jmduarte** [comment]
@oliviaweng @anmeza that sounds great. Yes, we should consolidate your hls4ml branch and @nicologhielmetti's branch.

Actually, we have a fork here: https://github.com/hls4ml-finn-mlperftiny/hls4ml, which is currently in sync with @nicologhielmetti's branch, so we can cherry-pick your changes and add it there as well once you have a branch.

**Comment by anmeza** [comment]
@jmduarte Sounds good. We'll merge the ReLU fusion optimization code into that fork once it's ready.
